---
title: "b_set_up_environment"
output: html_document
---
## Remember to open the R Project!!! ##
## Install packages with renv

Fiddly hack to make sure rlang is up to date: 
```{r}
install.packages("rlang") # Confirm that rlang is up to date.
```

```{r}
install.packages("Matrix")
```

```{r}
install.packages("purrr")
install.packages("zoo")
install.packages("splitstackshape")
install.packages("scales")
install.packages("haven")
install.packages("Epi")
install.packages("knitr")
install.packages("pspline")
install.packages("ggtern")
```
```{r}

install.packages("devtools") # To install epicoda from GitHub, the devtools package is required.  
library(devtools)
devtools::install_github("activityMonitoring/epicoda",  build_opts = c("--no-resave-data"), build_vignettes = TRUE, build_manual = TRUE)
```


Set up renv, the package manager for this project: 
```{r}
install.packages("renv")
renv::activate()
```

Use renv to restore packages from the lockfile: 
```{r}
renv::restore(prompt = FALSE)
.rs.restartR() # restart R after package update
# This may take some time
```
