---
title: "d_analyse_data"
format: html
editor: visual
---

## Load data

```{r}
library(data.table)
library(plyr)
library(dplyr)
library(magrittr)
library(lubridate)
library(readr)
library(survival)
library(Epi)
library(emmeans)
library(ggplot2)
#library(survminer)
#library(ckbplotr)
```

## Set-up useful functions

```{r}
source("rounding_functions.R")
source("cut_by_quantile.R")
source("cox_functions.R")
```

Data:

```{r}
dat <- fread("prepped_steps.csv", data.table = FALSE) # this file location assumes running in same session as previous script
datMRI <- fread("prepped_steps_MRI.csv", data.table = FALSE)
```

```{r}
dat <- dat %>%
  filter(total_prevalent_IA == TRUE)

```


```{r}
datMRI <- datMRI %>%
  filter(total_prevalent_PsO == TRUE)
```

```{r}
dat$step_thirds <- qtile_cut(dat$med_steps, probs = seq(0, 1, by = 1/3))
dat$acc_thirds <- qtile_cut(dat$overall_activity, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat$tdi_quarters <- qtile_cut(dat$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
dat$cadence30_thirds <- qtile_cut(dat$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=1/3))
dat$age_gp_crude <- cut(dat$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
dat$BMI_cats <-
  cut(dat$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<24.9", "25.0-29.9", "30.0+"),
      right = FALSE)
```


```{r}
exposures <- c("step_cats", "step_thirds", "acc_thirds","cadence30_thirds")
outcomes <- c("NAFLD_incident") 

multivar_covs <-
c(
"sex",
"ethnicity",
"tdi_quarters", 
"smoking",
"alcohol"
)

adjustments <-
list(
"model1" = NULL,
"model2" = c(multivar_covs),
"model3" = c(multivar_covs, "BMI_cats"),
"model4" = c(multivar_covs, "diabetes_charlson_CH")
)

```

```{r}
dir.create("outputs")
```



Cadence plotting
```{r}
for (exposure in exposures) {
  # SET UP RECORDING FRAME ======================================================
  results_columns <-   c("Exposure",
                         "Outcome",
                         "Model",
                         "Adjustment",
                         "n",
                         "n_event",
                         as.vector(outer(
                           # excessively complex code to get crossed column names
                           c(
                             "HR",
                             "Lower_CI",
                             "Upper_CI",
                             "floatedlnHR",
                             "floatedSE",
                             "floatedHR",
                             "floatedLower_CI",
                             "floatedUpper_CI",
                             "n",
                             "n_event", 
                             "mean_steps", 
                             "mean_acc",
                             "mean_cad30"
                           ),
                           unique(dat[, exposure]),
                           paste,
                           sep = "_"
                         )))
  results_tab <-
    data.frame(matrix(ncol = length(results_columns) ,
                      nrow = 0))
  colnames(results_tab) <- results_columns
  
  # Do modelling: ===============================================================
  for (i in 1:length(outcomes)) {
    for (j in 1:length(adjustments)) {
      # Pull relevant values-----------------------------
      outcome <- outcomes[i]
      model_name <- names(adjustments)[j]
      covs <- adjustments[[j]]
      
      # Organise for model calculation-------------------
      cov_sum <- paste0(c(exposure, covs), collapse = "+")
      
      # Model--------------------------------------------
      form <-
        paste0("Surv(age_entry_days, age_exit_days, ",
               outcome,
               ") ~ ",
               cov_sum)
      model <-
        coxph(as.formula(form), dat)
      print(cox.zph(model))
      
      # Extract values-----------------------------------
      results_frame <-
        data.frame(
          "Exposure" = exposure,
          "Outcome" = outcome,
          "Model" = model_name,
          "Adjustment" = paste0(covs, collapse = ","),
          "n" = model$n,
          "n_event" = model$nevent
        )
      
      # CYCLE THROUGH EXPOSURE LEVELS EXTRACTING INFO=============================================
      fac_levels <- levels(factor(dat[, exposure]))
      for (cat in fac_levels) {
        
        # HRs=====================================================================================
        if (cat == fac_levels[1]) {
          HRs <- data.frame(matrix(c(1, 1, 1), nrow = 1))
        }
        else {
          HRs <-
            summary(model)$conf.int[paste0(exposure, cat), c("exp(coef)", "lower .95", "upper .95"), drop = FALSE]
          rownames(HRs) <- NULL
        }
        colnames(HRs) <-
          as.vector(outer(c("HR", "Lower_CI", "Upper_CI"), cat, paste, sep = "_"))
        
        # FLOATED HRs etc =======================================================================
        float_model <- float(model)# This is doing floating absolute risks using Epi package
        
        ## Values
        zval <- qnorm(0.975)
        se <- sqrt(float_model$var[cat])
        lnhr <- float_model$coef[cat]
        
        # Collate into frame
        HRs_floated <-
          data.frame(matrix(c(
            lnhr,
            se,
            exp(lnhr),
            exp(lnhr - se[cat] * zval),
            exp(lnhr + se[cat] * zval)
          ), nrow = 1))
        colnames(HRs_floated) <-
          as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "floatedHR",
              "floatedLower_CI",
              "floatedUpper_CI"
            ),
            cat,
            paste,
            sep = "_"
          ))
    
        # n and nevent ===================================================================================
        n_group <- nrow(dat[dat[, exposure] == cat, ])
        n_event_group <- nrow(dat[(dat[, exposure] == cat) & (dat[, outcome]), ])
        n_by_group <- data.frame(matrix(c(n_group, n_event_group), nrow = 1))
        colnames(n_by_group) <-
          as.vector(outer(c("n", "n_event"), cat, paste, sep = "_"))
        
        # Mean exposure ==================================================================================
        col_me <- paste0("mean_steps_", cat)
        col_acc <- paste0("mean_acc_", cat)
        col_cad30 <- paste0("mean_cad30_", cat)
        mean_exposure <- data.frame(mean(dat$med_steps[dat[, exposure] == cat]), 
                                    mean(dat$overall_activity[dat[, exposure] == cat]),
                                    mean(dat$CadencePeak30Adjusted.steps.min.[dat[, exposure] == cat]))
        colnames(mean_exposure) <- c(col_me, col_acc,col_cad30)
        
        # Bind together in final data frame ==============================================================
        results_frame <-
          cbind(results_frame, HRs, HRs_floated, n_by_group, mean_exposure)
      }
      
      
      # CHECK THAT n and n events match by different routes
      nsum <- sum(results_frame[,  as.vector(outer(c("n"), fac_levels, paste, sep = "_"))])
      n_eventsum <- sum(results_frame[,  as.vector(outer(c("n_event"), fac_levels, paste, sep = "_"))])
      if ((results_frame$n != nsum)|(results_frame$n_event != n_eventsum)){
        stop("Mismatch between numbers derived from different sources. Recheck model. May be that some rows are being excluded due to missing covariate data.")
      }
      
      
      # BIND INTO FINAL RESULTS FRAME AND DELETE
      results_tab <- rbind(results_tab, results_frame)
      
      rm(results_frame)
      
    }
  }
  
  assign(paste0(exposure, "_results_tab"), results_tab)
  write.csv(results_tab, paste0("outputs/", exposure, "_tab.csv"))
  # print(results_tab)
  rm(results_tab, results_columns)
}
```


```{r}
sd(dat$med_steps) #3822.266
# Generate a standardization variable
dat$med_steps_std = (dat$med_steps - mean(dat$med_steps))/sd(dat$med_steps)
# Check distribution of variable
hist(dat$med_steps_std)
```

```{r}
sd(datMRI$med_steps) #3822.266
# Generate a standardization variable
datMRI$med_steps_std = (datMRI$med_steps - mean(datMRI$med_steps))/sd(datMRI$med_steps)
# Check distribution of variable
hist(datMRI$med_steps_std)
```


```{r}

cox_liver <- coxph((Surv(age_entry_days, age_exit_daysMRI, NAFLD_mri)) ~ 
                           med_steps_std + strata(sex)
                           + as.factor(tdi_quarters)
                           + as.factor(smoking) + as.factor(alcohol),
                         data=datMRI)

summary(cox_liver)
```

```{r}
datMRI$step_thirds <- qtile_cut(datMRI$med_steps, probs = seq(0, 1, by = 1/3))
datMRI$acc_thirds <- qtile_cut(datMRI$overall_activity, probs = seq(0, 1, by = 1/3), dp_label = 1)
datMRI$tdi_quarters <- qtile_cut(datMRI$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
datMRI$cadence30_thirds <- qtile_cut(datMRI$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=1/3))
datMRI$age_gp_crude <- cut(datMRI$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
datMRI$BMI_cats <- 
  cut(datMRI$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<24.9", "25.0-29.9", "30.0+"),
      right = FALSE)
```

```{r}
datMRI <- datMRI %>%
  filter(fu_timeMRI != 0)
```


```{r}
exposures <- c("step_cats", "step_thirds", "acc_thirds","cadence30_thirds")
outcomes <- c("NAFLD_mri") 

multivar_covs <-
c(
"sex",
"tdi_quarters", 
"smoking",
"alcohol"
)

adjustments <-
list(
"model1" = NULL,
"model2" = c(multivar_covs),
"model3" = c(multivar_covs, "BMI_cats"),
"model4" = c(multivar_covs, "diabetes_charlson_CH")
)

```

```{r}
dir.create("outputs")
```



Cadence plotting
```{r}
for (exposure in exposures) {
  # SET UP RECORDING FRAME ======================================================
  results_columns <-   c("Exposure",
                         "Outcome",
                         "Model",
                         "Adjustment",
                         "n",
                         "n_event",
                         as.vector(outer(
                           # excessively complex code to get crossed column names
                           c(
                             "HR",
                             "Lower_CI",
                             "Upper_CI",
                             "floatedlnHR",
                             "floatedSE",
                             "floatedHR",
                             "floatedLower_CI",
                             "floatedUpper_CI",
                             "n",
                             "n_event", 
                             "mean_steps", 
                             "mean_acc",
                             "mean_cad30"
                           ),
                           unique(datMRI[, exposure]),
                           paste,
                           sep = "_"
                         )))
  results_tab <-
    data.frame(matrix(ncol = length(results_columns) ,
                      nrow = 0))
  colnames(results_tab) <- results_columns
  
  # Do modelling: ===============================================================
  for (i in 1:length(outcomes)) {
    for (j in 1:length(adjustments)) {
      # Pull relevant values-----------------------------
      outcome <- outcomes[i]
      model_name <- names(adjustments)[j]
      covs <- adjustments[[j]]
      
      # Organise for model calculation-------------------
      cov_sum <- paste0(c(exposure, covs), collapse = "+")
      
      # Model--------------------------------------------
      form <-
        paste0("Surv(age_entry_days, age_exit_daysMRI, ",
               outcome,
               ") ~ ",
               cov_sum)
      model <-
        coxph(as.formula(form), datMRI)
      print(cox.zph(model))
      
      # Extract values-----------------------------------
      results_frame <-
        data.frame(
          "Exposure" = exposure,
          "Outcome" = outcome,
          "Model" = model_name,
          "Adjustment" = paste0(covs, collapse = ","),
          "n" = model$n,
          "n_event" = model$nevent
        )
      
      # CYCLE THROUGH EXPOSURE LEVELS EXTRACTING INFO=============================================
      fac_levels <- levels(factor(datMRI[, exposure]))
      for (cat in fac_levels) {
        
        # HRs=====================================================================================
        if (cat == fac_levels[1]) {
          HRs <- data.frame(matrix(c(1, 1, 1), nrow = 1))
        }
        else {
          HRs <-
            summary(model)$conf.int[paste0(exposure, cat), c("exp(coef)", "lower .95", "upper .95"), drop = FALSE]
          rownames(HRs) <- NULL
        }
        colnames(HRs) <-
          as.vector(outer(c("HR", "Lower_CI", "Upper_CI"), cat, paste, sep = "_"))
        
        # FLOATED HRs etc =======================================================================
        float_model <- float(model)# This is doing floating absolute risks using Epi package
        
        ## Values
        zval <- qnorm(0.975)
        se <- sqrt(float_model$var[cat])
        lnhr <- float_model$coef[cat]
        
        # Collate into frame
        HRs_floated <-
          data.frame(matrix(c(
            lnhr,
            se,
            exp(lnhr),
            exp(lnhr - se[cat] * zval),
            exp(lnhr + se[cat] * zval)
          ), nrow = 1))
        colnames(HRs_floated) <-
          as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "floatedHR",
              "floatedLower_CI",
              "floatedUpper_CI"
            ),
            cat,
            paste,
            sep = "_"
          ))
    
        # n and nevent ===================================================================================
        n_group <- nrow(datMRI[datMRI[, exposure] == cat, ])
        n_event_group <- nrow(datMRI[(datMRI[, exposure] == cat) & (datMRI[, outcome]), ])
        n_by_group <- data.frame(matrix(c(n_group, n_event_group), nrow = 1))
        colnames(n_by_group) <-
          as.vector(outer(c("n", "n_event"), cat, paste, sep = "_"))
        
        # Mean exposure ==================================================================================
        col_me <- paste0("mean_steps_", cat)
        col_acc <- paste0("mean_acc_", cat)
        col_cad30 <- paste0("mean_cad30_", cat)
        mean_exposure <- data.frame(mean(datMRI$med_steps[datMRI[, exposure] == cat]), 
                                    mean(datMRI$overall_activity[datMRI[, exposure] == cat]),
                                    mean(datMRI$CadencePeak30Adjusted.steps.min.[datMRI[, exposure] == cat]))
        colnames(mean_exposure) <- c(col_me, col_acc,col_cad30)
        
        # Bind together in final data frame ==============================================================
        results_frame <-
          cbind(results_frame, HRs, HRs_floated, n_by_group, mean_exposure)
      }
      
      
      # CHECK THAT n and n events match by different routes
      nsum <- sum(results_frame[,  as.vector(outer(c("n"), fac_levels, paste, sep = "_"))])
      n_eventsum <- sum(results_frame[,  as.vector(outer(c("n_event"), fac_levels, paste, sep = "_"))])
      if ((results_frame$n != nsum)|(results_frame$n_event != n_eventsum)){
        stop("Mismatch between numbers derived from different sources. Recheck model. May be that some rows are being excluded due to missing covariate data.")
      }
      
      
      # BIND INTO FINAL RESULTS FRAME AND DELETE
      results_tab <- rbind(results_tab, results_frame)
      
      rm(results_frame)
      
    }
  }
  
  assign(paste0(exposure, "_results_tab"), results_tab)
  write.csv(results_tab, paste0("outputs/", exposure, "_tab.csv"))
  # print(results_tab)
  rm(results_tab, results_columns)
}
```
