---
title: "plot_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(plyr)
library(dplyr)
library(magrittr)
library(lubridate)
library(readr)
library(survival)
library(Epi)
library(emmeans)
library(ggplot2)
#library(ckbplotr)
```

## Set-up useful functions


```{r}
source("rounding_functions.R")
source("cut_by_quantile.R")
source("cox_functions.R")
```

```{r}
dat <- fread("Data/prepped_steps.csv", data.table = FALSE) # this file location assumes running in same session as previous script
#dat2yr <- fread("Data/prepped_steps_RA2years.csv", data.table = FALSE)

```

```{r}
dat$step_quarters <- qtile_cut(dat$med_steps, probs = seq(0, 1, by = 0.25))
dat$acc_quarters <- qtile_cut(dat$overall_activity, probs = seq(0, 1, by = 0.25), dp_label = 1)
#dat$tdi_quarters <- qtile_cut(dat$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
dat$cadence30_quarters <- qtile_cut(dat$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=0.25))
dat$age_gp_crude <- cut(dat$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
dat$BMI_3level <-
  cut(dat$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<25", "25.0-29.9", "30.0+"),
      right = FALSE)
```

Subgroup out for each of the 3 BMI cats 

```{r}
datHealthy <- dat %>%
  filter(BMI_3level == "<25")
datOverweight <- dat %>%
  filter(BMI_3level == "25.0-29.9")
datObese <- dat %>%
  filter(BMI_3level == "30.0+")
```


Results: - select which sensitivity you want to run through 
```{r}
#step_quarters_results_tab <- fread("outputs/step_quarters_tabHealthyBMI.csv", data.table = FALSE) 
#step_quarters_results_tab <- fread("outputs/step_quarters_tabOverweight.csv", data.table = FALSE) 

step_quarters_results_tab <- fread("outputs/step_quarters_tabObese.csv", data.table = FALSE) 
```

Healthy BMI 
Organise results to plot and iteratively produce shape plots with different settings: 
```{r}
exposures <- c("step_quarters")
outcomes <- c("RA_incident")

adjustments <- unique(step_quarters_results_tab$Adjustment)

# CYCLE OVER ADJUSTMENTS=========================================
 for (adjustment in adjustments) {
   
  # CYCLE OVER OUTCOMES ============================
  for (outcome in outcomes) {
      
      # PROCESS OUTCOME NAME ======================================
      if (outcome == "RA_incident") {
        outcome_title <- "Incident RA"
      }  else {
        print(outcome)
        stop("Unrecognised outcome value")
      }
      
   
  # CYCLE OVER EXPOSURES =================================================
  for (exposure in exposures) {
    print(exposure)
      
  # PROCESS EXPOSURE NAME ==========================================
  if (exposure == "step_quarters") {
    exposure_title <- "Median Daily Steps"
  }
  else if (exposure == "acc_quarters") {
    exposure_title <- "Overall Acceleration (mg)"
  }
  else {
    stop("Unrecognised exposure value")
  }
  
  # GET RELEVANT DATASET =================================================
  tab <- get(paste0(exposure, "_results_tab"))
  
  
  
      # EXTRACT RELEVANT ELEMENTS OF DATASET=============================
      rel_tab <- tab[(tab$Outcome == outcome) & (tab$Adjustment == adjustment), , drop = FALSE]
      
      cols <- colnames(tab)[grepl("floatedlnHR_", colnames(tab))]
      cats <- sub("floatedlnHR_", "", cols)
        
      fp_frame <-
        data.frame(
          "exposure" = rep(exposure_title, length(cats)),
          "variable" = cats,
          "estimate" = rep(NA, length(cats)),
          "stderr" = rep(NA, length(cats)),
          "n" = rep(NA, length(cats)),
          "n_event" = rep(NA, length(cats))
        )
      for (cat in cats){
        fp_frame[fp_frame$variable == cat, c("estimate", "stderr", "n", "n_event", "mean_steps")] <- rel_tab[, as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "n", 
              "n_event", 
              "mean_steps"
            ),
            cat,
            paste,
            sep = "_"
          ))]
      }
      fp_frame$nlab <- format_thousand(fp_frame$n_event)
      fp_frame$estlab <- round_2_dp(exp(fp_frame$estimate)) 
      assign(paste0("fp_frame_", exposure, "_", outcome), fp_frame)
  }
  

  } 
   
   ## Set up for shape plots -------------------------------------------------------------------------------

  ### Manual --------------------------------------------------------------------------------------------
  # Allows fine-grained control over plot appearance
  rat_val <- 1.5
  size_val <- 14
  line_val <- 0.7
  textsize <- 4
  ext <- c(0, 0)
  lim_rad_scale <- 1/min(fp_frame_step_quarters_RA_incident$stderr) + 1
breaks <- seq(0, 2, by = 0.5)

# Calculate the limits for the y-axis
ylims <- c(min(breaks)-0.5, max(breaks)+0.01)
  xlims <- c(0, quantile(datHealthy$med_steps, 0.99))
  

#ylims <- c(0, 2)
#  xlims <- c(0, 20200)

  ruglinewidth <- 0.03
  datatoplot <- fp_frame_step_quarters_RA_incident
  
  # Create the plot with main aesthetics
shapeplot1 <- ggplot(datatoplot, aes(x = `mean_steps`, y = exp(estimate))) +

  # Plot the point estimates
  geom_point(aes(size = 1/stderr),
             shape = 15,
             colour = "black",
             fill = "black",
             stroke = 0.5) +
  
  # Plot point estimates text
  geom_text(aes(y = exp(estimate+1.96*stderr),
                label = estlab),
            vjust = -0.15,
            size  = textsize,
            colour = "black") +
  
  # Plot n events text
  geom_text(aes(y = exp(estimate-1.96*stderr),
                label = nlab),
            vjust = 1.15,
            size  = textsize,
            colour = "black") +
  
  # Plot the CIs
  geom_linerange(aes(ymin = exp(estimate-1.96*stderr),
                     ymax = exp(estimate+1.96*stderr)),
                 colour = "black",
                 linewidth = 0.5) +
  
  # Set the scale for the size of boxes
  scale_radius(guide  = "none",
               limits = c(0, lim_rad_scale),
               range  = c(0, 5)) +
  
  # Use identity for aesthetic scales
  scale_shape_identity() +
  scale_colour_identity() +
  scale_fill_identity() +
  
  # Set the y-axis scale
  scale_y_continuous(trans  = "log",
                     breaks = breaks) +
  scale_x_continuous(labels = function(x) {format_thousand(x)}) + 
  
  
  # Add titles
   xlab("Median Step Count") +
  ylab("HR for Incident RA") + 

 # Add rug plot
  geom_rug(data = datHealthy[datHealthy$med_steps < quantile(datHealthy$med_steps, 0.99), ], mapping = aes(x = med_steps), inherit.aes = FALSE, linewidth = ruglinewidth, alpha = 0.2,length = unit(0.015, "npc")) +
  theme(aspect.ratio = 1.8) +
  theme_bw()
  

  svg(paste0("outputs/shapeplot_stepquarters_", gsub(",", "_", adjustment), Sys.Date(), ".svg"), width = 10, height = 6)
  dev.off()
  
  assign(paste0("shapeplot_RA_incident_step_quartersHealthy_", gsub(",", "_", adjustment)), shapeplot1)
   }
```
# Spline plots

```{r}
outcomes <- c("RA_incident")

# All the set up of steps terms which can be done ahead of time ==============================
steps <- seq(quantile(datHealthy$med_steps, 0.01), quantile(datHealthy$med_steps, 0.99), length = 100)
spl <- pspline(datHealthy$med_steps, df=3)
quarter1 <- quantile(datHealthy$med_steps, 0.25)
step_ref <-  mean(datHealthy$med_steps[datHealthy$med_steps < quarter1]) #5112.999 use mean steps in lowest category so match 
spl_ref <- predict(spl, step_ref) # spline terms at reference value of variable
spl_all <- predict(spl, steps) # spline terms across steps
L <- t(spl_all) - c(spl_ref) # matrix of spline terms, centred for reference value of variable

# Loop to produce plots =====================================================================
for (outcome in outcomes){
  if (outcome == "RA_incident") {
        outcome_title <- "HR for Incident RA"
      }  else {
        print(outcome)
        stop("Unrecognised outcome value")
      }
  
  # MODEL ===============================================================================
form <- as.formula(paste0("Surv(age_entry_days, age_exit_days, ", outcome, ") ~ pspline(med_steps, df = 3) + sex + ethnicity+ qualif + smoking + alcohol + processed_meat + fresh_fruit + oily_fish"))
  model <- coxph(form, data = datHealthy)
  
 
  # MANUALLY CALCULATING SPLINE TERMS SO CAN SELECT REFERENCE ==========================
  step_terms <- names(model$coef)[grepl("med_steps", names(model$coef))]
  b <- model$coef[step_terms] ## coefficients for spline terms (the first ten terms in the model if specified as above)
  lnhr <- c(t(L) %*% b) # TO DO CHECK SAME AS PREDICTED
  varb <- vcov(model)[step_terms, step_terms] ## covariance matrix of spline coefficients
  varLb <- t(L) %*% varb %*% L
  SELb <- sqrt(diag(varLb))
  plot_dat <- data.frame(
    "med_steps" = steps,
    "lnhr" = lnhr,
    "se" = SELb,
    "hr" = exp(lnhr),
    "lowerCI" = exp(lnhr - 1.96 * SELb),
    "upperCI" = exp(lnhr + 1.96 * SELb)
  )
  
  plot_spline <- ggplot(plot_dat, aes(x = steps, y = hr))+
    geom_ribbon(aes(ymin = lowerCI,
                   ymax = upperCI),
              fill = "grey80")+
    geom_line(color = "black")+
        labs(y = outcome_title, x = " ")+
  geom_rug(data = datHealthy[datHealthy$med_steps < quantile(datHealthy$med_steps, 0.99), ], 
        mapping = aes(x = med_steps), inherit.aes = FALSE,linewidth = ruglinewidth,alpha=0.2,length = unit(0.015, "npc"))+
    
    scale_y_continuous(trans  = "log",
                     breaks = breaks) +
  scale_x_continuous(labels = function(x) {format_thousand(x)}) + 
    

    
    geom_hline(yintercept = 1, linetype = "dashed") +
    theme_bw() +
  xlab("Median Step Count") 
  
  
  plot_hist <- ggplot(datHealthy[datHealthy$med_steps < quantile(datHealthy$med_steps, 0.99), ], aes(x = med_steps))+ 
    geom_histogram() + labs(y = "Count", x = "Daily Step Count")
  
}
```


Overweight

```{r}
exposures <- c("step_quarters")
outcomes <- c("RA_incident")

adjustments <- unique(step_quarters_results_tab$Adjustment)

# CYCLE OVER ADJUSTMENTS=========================================
 for (adjustment in adjustments) {
   
  # CYCLE OVER OUTCOMES ============================
  for (outcome in outcomes) {
      
      # PROCESS OUTCOME NAME ======================================
      if (outcome == "RA_incident") {
        outcome_title <- "Incident RA"
      }  else {
        print(outcome)
        stop("Unrecognised outcome value")
      }
      
   
  # CYCLE OVER EXPOSURES =================================================
  for (exposure in exposures) {
    print(exposure)
      
  # PROCESS EXPOSURE NAME ==========================================
  if (exposure == "step_quarters") {
    exposure_title <- "Median Daily Steps"
  }
  else if (exposure == "acc_quarters") {
    exposure_title <- "Overall Acceleration (mg)"
  }
  else {
    stop("Unrecognised exposure value")
  }
  
  # GET RELEVANT DATASET =================================================
  tab <- get(paste0(exposure, "_results_tab"))
  
  
  
      # EXTRACT RELEVANT ELEMENTS OF DATASET=============================
      rel_tab <- tab[(tab$Outcome == outcome) & (tab$Adjustment == adjustment), , drop = FALSE]
      
      cols <- colnames(tab)[grepl("floatedlnHR_", colnames(tab))]
      cats <- sub("floatedlnHR_", "", cols)
        
      fp_frame <-
        data.frame(
          "exposure" = rep(exposure_title, length(cats)),
          "variable" = cats,
          "estimate" = rep(NA, length(cats)),
          "stderr" = rep(NA, length(cats)),
          "n" = rep(NA, length(cats)),
          "n_event" = rep(NA, length(cats))
        )
      for (cat in cats){
        fp_frame[fp_frame$variable == cat, c("estimate", "stderr", "n", "n_event", "mean_steps")] <- rel_tab[, as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "n", 
              "n_event", 
              "mean_steps"
            ),
            cat,
            paste,
            sep = "_"
          ))]
      }
      fp_frame$nlab <- format_thousand(fp_frame$n_event)
      fp_frame$estlab <- round_2_dp(exp(fp_frame$estimate)) 
      assign(paste0("fp_frame_", exposure, "_", outcome), fp_frame)
  }
  

  } 
   
   ## Set up for shape plots -------------------------------------------------------------------------------

  ### Manual --------------------------------------------------------------------------------------------
  # Allows fine-grained control over plot appearance
  rat_val <- 1.5
  size_val <- 14
  line_val <- 0.7
  textsize <- 4
  ext <- c(0, 0)
  lim_rad_scale <- 1/min(fp_frame_step_quarters_RA_incident$stderr) + 1
breaks <- seq(0, 2, by = 0.5)

# Calculate the limits for the y-axis
ylims <- c(min(breaks)-0.5, max(breaks)+0.01)
  xlims <- c(0, quantile(datOverweight$med_steps, 0.99))
  

#ylims <- c(0, 2)
#  xlims <- c(0, 20200)

  ruglinewidth <- 0.03
  datatoplot <- fp_frame_step_quarters_RA_incident
  
  # Create the plot with main aesthetics
shapeplot1 <- ggplot(datatoplot, aes(x = `mean_steps`, y = exp(estimate))) +

  # Plot the point estimates
  geom_point(aes(size = 1/stderr),
             shape = 15,
             colour = "black",
             fill = "black",
             stroke = 0.5) +
  
  # Plot point estimates text
  geom_text(aes(y = exp(estimate+1.96*stderr),
                label = estlab),
            vjust = -0.15,
            size  = textsize,
            colour = "black") +
  
  # Plot n events text
  geom_text(aes(y = exp(estimate-1.96*stderr),
                label = nlab),
            vjust = 1.15,
            size  = textsize,
            colour = "black") +
  
  # Plot the CIs
  geom_linerange(aes(ymin = exp(estimate-1.96*stderr),
                     ymax = exp(estimate+1.96*stderr)),
                 colour = "black",
                 linewidth = 0.5) +
  
  # Set the scale for the size of boxes
  scale_radius(guide  = "none",
               limits = c(0, lim_rad_scale),
               range  = c(0, 5)) +
  
  # Use identity for aesthetic scales
  scale_shape_identity() +
  scale_colour_identity() +
  scale_fill_identity() +
  
  # Set the y-axis scale
  scale_y_continuous(trans  = "log",
                     breaks = breaks) +
  scale_x_continuous(labels = function(x) {format_thousand(x)}) + 
  
  
  # Add titles
   xlab("Median Step Count") +
  ylab("HR for Incident RA") + 

 # Add rug plot
  geom_rug(data = datOverweight[datOverweight$med_steps < quantile(datOverweight$med_steps, 0.99), ], mapping = aes(x = med_steps), inherit.aes = FALSE, linewidth = ruglinewidth, alpha = 0.2,length = unit(0.015, "npc")) +
  theme(aspect.ratio = 1.8) +
  theme_bw()
  

  svg(paste0("outputs/shapeplot_stepquarters_", gsub(",", "_", adjustment), Sys.Date(), ".svg"), width = 10, height = 6)
  dev.off()
  
  assign(paste0("shapeplot_RA_incident_step_quartersOverweight_", gsub(",", "_", adjustment)), shapeplot1)
   }
```

# Spline plots overweight

```{r}
outcomes <- c("RA_incident")

# All the set up of steps terms which can be done ahead of time ==============================
steps <- seq(quantile(datOverweight$med_steps, 0.01), quantile(datOverweight$med_steps, 0.99), length = 100)
spl <- pspline(datOverweight$med_steps, df=3)
quarter1 <- quantile(datOverweight$med_steps, 0.25)
step_ref <-  mean(datOverweight$med_steps[datOverweight$med_steps < quarter1]) #5112.999 use mean steps in lowest category so match 
spl_ref <- predict(spl, step_ref) # spline terms at reference value of variable
spl_all <- predict(spl, steps) # spline terms across steps
L <- t(spl_all) - c(spl_ref) # matrix of spline terms, centred for reference value of variable

# Loop to produce plots =====================================================================
for (outcome in outcomes){
  if (outcome == "RA_incident") {
        outcome_title <- "HR for Incident RA"
      }  else {
        print(outcome)
        stop("Unrecognised outcome value")
      }
  
  # MODEL ===============================================================================
form <- as.formula(paste0("Surv(age_entry_days, age_exit_days, ", outcome, ") ~ pspline(med_steps, df = 3) + sex + ethnicity+ qualif + smoking + alcohol + processed_meat + fresh_fruit + oily_fish"))
  model <- coxph(form, data = datOverweight)
  
 
  # MANUALLY CALCULATING SPLINE TERMS SO CAN SELECT REFERENCE ==========================
  step_terms <- names(model$coef)[grepl("med_steps", names(model$coef))]
  b <- model$coef[step_terms] ## coefficients for spline terms (the first ten terms in the model if specified as above)
  lnhr <- c(t(L) %*% b) # TO DO CHECK SAME AS PREDICTED
  varb <- vcov(model)[step_terms, step_terms] ## covariance matrix of spline coefficients
  varLb <- t(L) %*% varb %*% L
  SELb <- sqrt(diag(varLb))
  plot_dat <- data.frame(
    "med_steps" = steps,
    "lnhr" = lnhr,
    "se" = SELb,
    "hr" = exp(lnhr),
    "lowerCI" = exp(lnhr - 1.96 * SELb),
    "upperCI" = exp(lnhr + 1.96 * SELb)
  )
  
  plot_spline <- ggplot(plot_dat, aes(x = steps, y = hr))+
    geom_ribbon(aes(ymin = lowerCI,
                   ymax = upperCI),
              fill = "grey80")+
    geom_line(color = "black")+
        labs(y = outcome_title, x = " ")+
  geom_rug(data = datOverweight[datOverweight$med_steps < quantile(datOverweight$med_steps, 0.99), ], 
        mapping = aes(x = med_steps), inherit.aes = FALSE,linewidth = ruglinewidth,alpha=0.2,length = unit(0.015, "npc"))+
    
    scale_y_continuous(trans  = "log",
                     breaks = breaks) +
  scale_x_continuous(labels = function(x) {format_thousand(x)}) + 
    

    
    geom_hline(yintercept = 1, linetype = "dashed") +
    theme_bw() +
  xlab("Median Step Count") 
  
  
  plot_hist <- ggplot(datOverweight[datOverweight$med_steps < quantile(datOverweight$med_steps, 0.99), ], aes(x = med_steps))+ 
    geom_histogram() + labs(y = "Count", x = "Daily Step Count")
  
}
```



Obese shape plot

```{r}
exposures <- c("step_quarters")
outcomes <- c("RA_incident")

adjustments <- unique(step_quarters_results_tab$Adjustment)

# CYCLE OVER ADJUSTMENTS=========================================
 for (adjustment in adjustments) {
   
  # CYCLE OVER OUTCOMES ============================
  for (outcome in outcomes) {
      
      # PROCESS OUTCOME NAME ======================================
      if (outcome == "RA_incident") {
        outcome_title <- "Incident RA"
      }  else {
        print(outcome)
        stop("Unrecognised outcome value")
      }
      
   
  # CYCLE OVER EXPOSURES =================================================
  for (exposure in exposures) {
    print(exposure)
      
  # PROCESS EXPOSURE NAME ==========================================
  if (exposure == "step_quarters") {
    exposure_title <- "Median Daily Steps"
  }
  else if (exposure == "acc_quarters") {
    exposure_title <- "Overall Acceleration (mg)"
  }
  else {
    stop("Unrecognised exposure value")
  }
  
  # GET RELEVANT DATASET =================================================
  tab <- get(paste0(exposure, "_results_tab"))
  
  
  
      # EXTRACT RELEVANT ELEMENTS OF DATASET=============================
      rel_tab <- tab[(tab$Outcome == outcome) & (tab$Adjustment == adjustment), , drop = FALSE]
      
      cols <- colnames(tab)[grepl("floatedlnHR_", colnames(tab))]
      cats <- sub("floatedlnHR_", "", cols)
        
      fp_frame <-
        data.frame(
          "exposure" = rep(exposure_title, length(cats)),
          "variable" = cats,
          "estimate" = rep(NA, length(cats)),
          "stderr" = rep(NA, length(cats)),
          "n" = rep(NA, length(cats)),
          "n_event" = rep(NA, length(cats))
        )
      for (cat in cats){
        fp_frame[fp_frame$variable == cat, c("estimate", "stderr", "n", "n_event", "mean_steps")] <- rel_tab[, as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "n", 
              "n_event", 
              "mean_steps"
            ),
            cat,
            paste,
            sep = "_"
          ))]
      }
      fp_frame$nlab <- format_thousand(fp_frame$n_event)
      fp_frame$estlab <- round_2_dp(exp(fp_frame$estimate)) 
      assign(paste0("fp_frame_", exposure, "_", outcome), fp_frame)
  }
  

  } 
   
   ## Set up for shape plots -------------------------------------------------------------------------------

  ### Manual --------------------------------------------------------------------------------------------
  # Allows fine-grained control over plot appearance
  rat_val <- 1.5
  size_val <- 14
  line_val <- 0.7
  textsize <- 4
  ext <- c(0, 0)
  lim_rad_scale <- 1/min(fp_frame_step_quarters_RA_incident$stderr) + 1
breaks <- seq(0, 2, by = 0.5)

# Calculate the limits for the y-axis
ylims <- c(min(breaks)-0.5, max(breaks)+0.01)
  xlims <- c(0, quantile(datObese$med_steps, 0.99))
  

#ylims <- c(0, 2)
#  xlims <- c(0, 20200)

  ruglinewidth <- 0.03
  datatoplot <- fp_frame_step_quarters_RA_incident
  
  # Create the plot with main aesthetics
shapeplot1 <- ggplot(datatoplot, aes(x = `mean_steps`, y = exp(estimate))) +

  # Plot the point estimates
  geom_point(aes(size = 1/stderr),
             shape = 15,
             colour = "black",
             fill = "black",
             stroke = 0.5) +
  
  # Plot point estimates text
  geom_text(aes(y = exp(estimate+1.96*stderr),
                label = estlab),
            vjust = -0.15,
            size  = textsize,
            colour = "black") +
  
  # Plot n events text
  geom_text(aes(y = exp(estimate-1.96*stderr),
                label = nlab),
            vjust = 1.15,
            size  = textsize,
            colour = "black") +
  
  # Plot the CIs
  geom_linerange(aes(ymin = exp(estimate-1.96*stderr),
                     ymax = exp(estimate+1.96*stderr)),
                 colour = "black",
                 linewidth = 0.5) +
  
  # Set the scale for the size of boxes
  scale_radius(guide  = "none",
               limits = c(0, lim_rad_scale),
               range  = c(0, 5)) +
  
  # Use identity for aesthetic scales
  scale_shape_identity() +
  scale_colour_identity() +
  scale_fill_identity() +
  
  # Set the y-axis scale
  scale_y_continuous(trans  = "log",
                     breaks = breaks) +
  scale_x_continuous(labels = function(x) {format_thousand(x)}) + 
  
  
  # Add titles
   xlab("Median Step Count") +
  ylab("HR for Incident RA") + 

 # Add rug plot
  geom_rug(data = datObese[datObese$med_steps < quantile(datObese$med_steps, 0.99), ], mapping = aes(x = med_steps), inherit.aes = FALSE, linewidth = ruglinewidth, alpha = 0.2,length = unit(0.015, "npc")) +
  theme(aspect.ratio = 1.8) +
  theme_bw()
  

  svg(paste0("outputs/shapeplot_stepquarters_", gsub(",", "_", adjustment), Sys.Date(), ".svg"), width = 10, height = 6)
  dev.off()
  
  assign(paste0("shapeplot_RA_incident_step_quartersObese_", gsub(",", "_", adjustment)), shapeplot1)
   }
```


# Spline plots Obese

```{r}
outcomes <- c("RA_incident")

# All the set up of steps terms which can be done ahead of time ==============================
steps <- seq(quantile(datObese$med_steps, 0.01), quantile(datObese$med_steps, 0.99), length = 100)
spl <- pspline(datObese$med_steps, df=3)
quarter1 <- quantile(datObese$med_steps, 0.25)
step_ref <-  mean(datObese$med_steps[datObese$med_steps < quarter1]) #5112.999 use mean steps in lowest category so match 
spl_ref <- predict(spl, step_ref) # spline terms at reference value of variable
spl_all <- predict(spl, steps) # spline terms across steps
L <- t(spl_all) - c(spl_ref) # matrix of spline terms, centred for reference value of variable

# Loop to produce plots =====================================================================
for (outcome in outcomes){
  if (outcome == "RA_incident") {
        outcome_title <- "HR for Incident RA"
      }  else {
        print(outcome)
        stop("Unrecognised outcome value")
      }
  
  # MODEL ===============================================================================
form <- as.formula(paste0("Surv(age_entry_days, age_exit_days, ", outcome, ") ~ pspline(med_steps, df = 3) + sex + ethnicity+ qualif + smoking + alcohol + processed_meat + fresh_fruit + oily_fish"))
  model <- coxph(form, data = datObese)
  
 
  # MANUALLY CALCULATING SPLINE TERMS SO CAN SELECT REFERENCE ==========================
  step_terms <- names(model$coef)[grepl("med_steps", names(model$coef))]
  b <- model$coef[step_terms] ## coefficients for spline terms (the first ten terms in the model if specified as above)
  lnhr <- c(t(L) %*% b) # TO DO CHECK SAME AS PREDICTED
  varb <- vcov(model)[step_terms, step_terms] ## covariance matrix of spline coefficients
  varLb <- t(L) %*% varb %*% L
  SELb <- sqrt(diag(varLb))
  plot_dat <- data.frame(
    "med_steps" = steps,
    "lnhr" = lnhr,
    "se" = SELb,
    "hr" = exp(lnhr),
    "lowerCI" = exp(lnhr - 1.96 * SELb),
    "upperCI" = exp(lnhr + 1.96 * SELb)
  )
  
  plot_spline <- ggplot(plot_dat, aes(x = steps, y = hr))+
    geom_ribbon(aes(ymin = lowerCI,
                   ymax = upperCI),
              fill = "grey80")+
    geom_line(color = "black")+
        labs(y = outcome_title, x = " ")+
  geom_rug(data = datObese[datObese$med_steps < quantile(datObese$med_steps, 0.99), ], 
        mapping = aes(x = med_steps), inherit.aes = FALSE,linewidth = ruglinewidth,alpha=0.2,length = unit(0.015, "npc"))+
    
    scale_y_continuous(trans  = "log",
                     breaks = breaks) +
  scale_x_continuous(labels = function(x) {format_thousand(x)}) + 
    

    
    geom_hline(yintercept = 1, linetype = "dashed") +
    theme_bw() +
  xlab("Median Step Count") 
  
  
  plot_hist <- ggplot(datObese[datObese$med_steps < quantile(datObese$med_steps, 0.99), ], aes(x = med_steps))+ 
    geom_histogram() + labs(y = "Count", x = "Daily Step Count")
  
}
```



