---
title: "CleaningGPdata"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# First we need to install packages that aren't already present
pkgs <- c("data.table", "plyr", "dplyr","ggplot2") # packages we need
pkgs_inst <- pkgs[!{pkgs %in% rownames(installed.packages())}] # check which are not present 
install.packages(pkgs_inst, repos = "https://www.stats.bris.ac.uk/R/") # install

# Load packages
lapply(pkgs, library, character.only = TRUE) # using lapply just allows us to load several packages on one line - this could be replaced with several calls to library()
```



```{bash}
cd ~/rap_wearables

dx download /users/mcgaghd/PrimaryCare/PrimaryCareClean -r
dx download /users/mcgaghd/Data -r
```


```{r}
datPsO_v2 <- fread("PrimaryCareClean/PsO_Read2.csv", data.table = FALSE) # fread is a function from the data.table package for fast reading of large data
datPsO_v3 <- fread("PrimaryCareClean/PsO_Read3.csv", data.table = FALSE)
datPsA_v2 <- fread("PrimaryCareClean/PsA_Read2.csv", data.table = FALSE)
datPsA_v3 <- fread("PrimaryCareClean/PsA_Read3.csv", data.table = FALSE)

datPsO_v2 <- datPsO_v2 %>%
  filter(!is.na(event_dt))
datPsO_v2[is.na(datPsO_v2)] <- ""

datPsO_v3 <- datPsO_v3 %>%
  filter(!is.na(event_dt))
datPsO_v3[is.na(datPsO_v3)] <- ""

datPsA_v2 <- datPsA_v2 %>%
  filter(!is.na(event_dt))
datPsA_v2[is.na(datPsA_v2)] <- ""

datPsA_v3 <- datPsA_v3 %>%
  filter(!is.na(event_dt))
datPsA_v3[is.na(datPsA_v3)] <- ""
```


Data cleaning. As we're confident in our codes from data extract script. We can just create a ew column of Psoriasis T/F or PsA TRUE/FALSE

```{r}
datPsO_v2$gp_PsO <- TRUE
datPsO_v3$gp_PsO <- TRUE

datPsA_v2$gp_PsA <- TRUE
datPsA_v3$gp_PsA <- TRUE
```

PsA 
```{r}
datPsA_v2_subset <- datPsA_v2[, c("V1","eid", "data_provider", "event_dt", "gp_PsA")]
datPsA_v3_subset <- datPsA_v3[, c("V1","eid", "data_provider", "event_dt", "gp_PsA")]

# Append the two dataframes together
datPsA_gp <- rbind(datPsA_v2_subset, datPsA_v3_subset)
```

Psoriasis
```{r}
datPsO_v2_subset <- datPsO_v2[, c("V1","eid", "data_provider", "event_dt", "gp_PsO")]
datPsO_v3_subset <- datPsO_v3[, c("V1","eid", "data_provider", "event_dt", "gp_PsO")]

# Append the two dataframes together
datPsO_gp <- rbind(datPsO_v2_subset, datPsO_v3_subset)
```