---
title: "d_analyse_data"
format: html
editor: visual
---

## Load data

```{r}
library(data.table)
library(plyr)
library(dplyr)
library(magrittr)
library(lubridate)
library(readr) 
library(survival)
library(Epi)
#library(emmeans)
library(ggplot2)
#library(survminer)
#library(ckbplotr)
```

## Set-up useful functions

```{r}
source("rounding_functions.R")
source("cut_by_quantile.R")
source("cox_functions.R")
```

Data:

```{bash}
cd ~/rap_wearables

dx download /users/mcgaghd/PsAfinal -r
dx download /users/mcgaghd/methotrexate.csv -r
```

```{r}
dat <- fread("PsAfinal/prepped_steps_PsAfinal.csv", data.table = FALSE)

dat$V1 <- NULL
```


```{r}
# Now you can proceed with your filter operation

dat <- dat %>%
  filter(total_prevalent_PsO == TRUE)

```

```{r}
primary <- "med_steps"
dat$med_steps_std <- standardise_column(dat[[primary]], 1000, TRUE)
hist(dat$med_steps_std)
```
Make venn diagram for supplemental 
```{r}
library(ggvenn)
datPsO_venn <- dat[dat$Prevalent_PsO_lessPsA == TRUE, ]

datPsO_venn$'Self-report' <- datPsO_venn$self_reported_PsO
datPsO_venn$'HES coded' <- datPsO_venn$hes_prevalent_PsO
datPsO_venn$'Primary care coded' <- datPsO_venn$PrevalentPsO_gp


plot <- ggvenn(datPsO_venn, c('Self-report', 'HES coded', 'Primary care coded'),
               fill_color = c("#0073C2FF", "#EFC000FF", "#CD534CFF"),
  stroke_size = 0.5, set_name_size = 4
  )
plot

```

```{r}
dir.create("plots")
output_dir <- "plots"
output_file <- file.path(output_dir, "PsO_venn.tiff")
ggsave(output_file, plot, device = "tiff", width = 6, height = 6, dpi = 300)
```

Sequentially run this - for sensitivity analysis
```{r}
TwoYear_cases <- (dat$PsATotal_incident & dat$fu_time <= 730)

dat2yr <- dat[!(TwoYear_cases), ]

```

```{r}
FourYear_cases <- (dat$PsATotal_incident & dat$fu_time <= 1461)

dat4yr <- dat[!(FourYear_cases), ]

```

```{r}
ThreeYear_cases <- (dat$PsATotal_incident & dat$fu_time <= 1096)

dat3yr <- dat[!(ThreeYear_cases), ]

```



```{r}

dat <- dat %>%
  mutate(step_thirdsEqual = case_when(
    med_steps < 5000 ~ "<5000",
    med_steps >= 5000 & med_steps <= 10000 ~ "5000-10000",
    med_steps > 10000 ~ ">10000"
  ))

dat$step_thirds <- qtile_cut(dat$med_steps, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat$step_quartiles <- qtile_cut(dat$med_steps, probs = seq(0, 1, by = 1/4), dp_label = 1)
dat$step_quintiles <- qtile_cut(dat$med_steps, probs = seq(0, 1, by = 1/5), dp_label = 1)

dat$acc_thirds <- qtile_cut(dat$overall_activity, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat$tdi_quarters <- qtile_cut(dat$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
dat$cadence30_thirds <- qtile_cut(dat$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=1/3))
dat$age_gp_crude <- cut(dat$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
dat$age_2cat <- cut(dat$age_entry_years, seq(40, 80, by = 20), right = FALSE, labels = c("40-59", "60-79"))
dat$BMI_cats <-
  cut(dat$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<24.9", "25.0-29.9", "30.0+"),
      right = FALSE)
```


## Table

```{r}
# MAKE SURE FACTORS NEATLY ORGANISED ================================================
dat$smoking <-
  factor(dat$smoking,
         levels = c("Never", "Previous", "Current"),
         ordered = TRUE)
dat$qualif <-
  factor(
    dat$qualif,
    ordered = TRUE,
    levels = c("School leaver", "Further education", "Higher education")
  )

dat$season_wear <-
  factor(
    dat$season_wear,
    ordered = TRUE,
    levels = c("Spring", "Summer", "Autumn", "Winter")
  )

dat$alcohol <-
  factor(
    dat$alcohol,
    ordered = TRUE,
    levels = c("Never", "<3 times/week", "3+ times/week")
  )


# Set cadence to zero if NA


# FUNCTIONS FOR EXTRACTING NUMBERS======================================================
source("format_for_table.R")

# TABLE 1======================================================
## FIRST ROW
table1 <-
  cbind(data.frame(
    "Characteristic" = c("Overall"),
    "Group" = c(" ")), get_table_numbers(dat, dat)
  )

## LIST AND ITERATE THROUGH VARIABLES 
varlist <-
  list(
    "Sex" = "sex",
    "Age (in groups)" = "age_gp_crude",
    "Quarter of Townsend Deprivation Index" = "tdi_quarters",
    "Educational Qualifications" = "qualif",
    "Smoking Status" = "smoking",
    "Alcohol Consumption" = "alcohol",
    "BMI (kg/m2)" = "BMI_cats",
    "Wear Season" = "season_wear", 
    "Use of systemic treatments" = "SystemicTreatment"
  )

for (name in names(varlist)) {
  print(name)
 
  variable <- varlist[[name]]
  dat[, variable] <- factor(dat[, variable]) # ensure factors
  factor_levels <- levels(dat[, variable])
  
  for (level in factor_levels) {
    # GET LOCAL DATASET
    dat_loc <- dat[dat[, variable] == level, ]
    
    # FILL OUT VARS FOR DATA FRAME
    char <-
      ifelse(level == factor_levels[1], name, "") # assign characteristic name only for first
    table1_numbers <- get_table_numbers(dat_loc, dat)
    
    # MAKE INTO TABLE
    table1_row <- cbind(
      data.frame(
        "Characteristic" = char,
        "Group" = level), table1_numbers
       
      )
    table1 <- rbind(table1, table1_row)
    
    
    # TIDY
    rm(char,
       dat_loc,
       table1_numbers,
       table1_row)
  }
  # TIDY
  rm(factor_levels, variable)
  
}

write.csv(table1, paste0("outputs/table1_rw_", Sys.Date(), ".csv"), row.names = FALSE)
```
Get median follow up time and age of the cohort at accelerometer wear. 
```{r}
# Calculate the median of age_entry_years

dat$age_entry_years_numeric <- as.numeric(as.character(dat$age_entry_years))

median_age <- median(dat$age_entry_years_numeric, na.rm = TRUE)

# Calculate the interquartile range of age_entry_years
iqr_age <- IQR(dat$age_entry_years_numeric, na.rm = TRUE)

# Display the results
cat("Median of age_entry_years:", median_age, "\n")
cat("Interquartile Range (IQR) of age_entry_years:", iqr_age, "\n")

median_age <- 63.9
iqr_age <- 12.033

# Calculate the first and third quartiles
Q1 <- median_age - (iqr_age / 2)
Q3 <- median_age + (iqr_age / 2)

# Format the output string
output <- sprintf("%.1f (IQR: %.1f–%.1f) years", median_age, Q1, Q3)

# Print the formatted output
print(output)
```

```{r}
# Convert fu_time from days to years
dat$fu_time_years <- dat$fu_time / 365.25

# Calculate the mean of fu_time in years
mean_fu_time_years <- mean(dat$fu_time_years, na.rm = TRUE)

# Calculate the standard deviation of fu_time in years
sd_fu_time_years <- sd(dat$fu_time_years, na.rm = TRUE)

# Format and print the results
output <- sprintf("Mean (SD) years: %.2f (%.2f)", mean_fu_time_years, sd_fu_time_years)
print(output)

```

Report figures for medications 
```{r}
library(ggvenn)



# Prepare the dataset for the Venn diagram
dat_venn <- dat %>%
  dplyr::select(MTX_any, ciclosporin_any, acitretin_any, bDMARD_any)

dat_venn$'Methotrexate' <-dat_venn$MTX_any 
dat_venn$'Ciclosporin' <- dat_venn$ciclosporin_any  
dat_venn$'Acitretin' <- dat_venn$acitretin_any
dat_venn$'Biologic DMARD' <- dat_venn$bDMARD_any


# Create the Venn diagram
ggvenn(dat_venn, c("Methotrexate", "Ciclosporin", "Acitretin", "Biologic DMARD"))
```

```{r}
exposures <- c("step_cats", "step_thirds","step_quartiles", "step_quintiles",
               "step_thirdsEqual", "acc_thirds","cadence30_thirds")
outcomes <- c("PsATotal_incident") 

multivar_covs <-
c(
"sex",
"tdi_quarters", 
"qualif",
"smoking",
"alcohol"
)

adjustments <-
list(
"model1" = NULL,
"model2" = c(multivar_covs),
"model3" = c(multivar_covs, "BMI_cats"),
"model3" = c(multivar_covs, "SystemicTreatment")
)

```

```{r}
dir.create("outputs")
```

Cadence plotting
```{r}
for (exposure in exposures) {
  # SET UP RECORDING FRAME ======================================================
  results_columns <-   c("Exposure",
                         "Outcome",
                         "Model",
                         "Adjustment",
                         "n",
                         "n_event",
                         as.vector(outer(
                           # excessively complex code to get crossed column names
                           c(
                             "HR",
                             "Lower_CI",
                             "Upper_CI",
                             "floatedlnHR",
                             "floatedSE",
                             "floatedHR",
                             "floatedLower_CI",
                             "floatedUpper_CI",
                             "n",
                             "n_event", 
                             "mean_steps", 
                             "mean_acc",
                             "mean_cad30"
                           ),
                           unique(dat[, exposure]),
                           paste,
                           sep = "_"
                         )))
  results_tab <-
    data.frame(matrix(ncol = length(results_columns) ,
                      nrow = 0))
  colnames(results_tab) <- results_columns
  
  # Do modelling: ===============================================================
  for (i in 1:length(outcomes)) {
    for (j in 1:length(adjustments)) {
      # Pull relevant values-----------------------------
      outcome <- outcomes[i]
      model_name <- names(adjustments)[j]
      covs <- adjustments[[j]]
      
      # Organise for model calculation-------------------
      cov_sum <- paste0(c(exposure, covs), collapse = "+")
      
      # Model--------------------------------------------
      form <-
        paste0("Surv(age_entry_days, age_exit_days, ",
               outcome,
               ") ~ ",
               cov_sum)
      model <-
        coxph(as.formula(form), dat)
      print(cox.zph(model))
      
      # Extract values-----------------------------------
      results_frame <-
        data.frame(
          "Exposure" = exposure,
          "Outcome" = outcome,
          "Model" = model_name,
          "Adjustment" = paste0(covs, collapse = ","),
          "n" = model$n,
          "n_event" = model$nevent
        )
      
      # CYCLE THROUGH EXPOSURE LEVELS EXTRACTING INFO=============================================
      fac_levels <- levels(factor(dat[, exposure]))
      for (cat in fac_levels) {
        
        # HRs=====================================================================================
        if (cat == fac_levels[1]) {
          HRs <- data.frame(matrix(c(1, 1, 1), nrow = 1))
        }
        else {
          HRs <-
            summary(model)$conf.int[paste0(exposure, cat), c("exp(coef)", "lower .95", "upper .95"), drop = FALSE]
          rownames(HRs) <- NULL
        }
        colnames(HRs) <-
          as.vector(outer(c("HR", "Lower_CI", "Upper_CI"), cat, paste, sep = "_"))
        
        # FLOATED HRs etc =======================================================================
        float_model <- float(model)# This is doing floating absolute risks using Epi package
        
        ## Values
        zval <- qnorm(0.975)
        se <- sqrt(float_model$var[cat])
        lnhr <- float_model$coef[cat]
        
        # Collate into frame
        HRs_floated <-
          data.frame(matrix(c(
            lnhr,
            se,
            exp(lnhr),
            exp(lnhr - se[cat] * zval),
            exp(lnhr + se[cat] * zval)
          ), nrow = 1))
        colnames(HRs_floated) <-
          as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "floatedHR",
              "floatedLower_CI",
              "floatedUpper_CI"
            ),
            cat,
            paste,
            sep = "_"
          ))
    
        # n and nevent ===================================================================================
        n_group <- nrow(dat[dat[, exposure] == cat, ])
        n_event_group <- nrow(dat[(dat[, exposure] == cat) & (dat[, outcome]), ])
        n_by_group <- data.frame(matrix(c(n_group, n_event_group), nrow = 1))
        colnames(n_by_group) <-
          as.vector(outer(c("n", "n_event"), cat, paste, sep = "_"))
        
        # Mean exposure ==================================================================================
        col_me <- paste0("mean_steps_", cat)
        col_acc <- paste0("mean_acc_", cat)
        col_cad30 <- paste0("mean_cad30_", cat)
        mean_exposure <- data.frame(mean(dat$med_steps[dat[, exposure] == cat]), 
                                    mean(dat$overall_activity[dat[, exposure] == cat]),
                                    mean(dat$CadencePeak30Adjusted.steps.min.[dat[, exposure] == cat]))
        colnames(mean_exposure) <- c(col_me, col_acc,col_cad30)
        
        # Bind together in final data frame ==============================================================
        results_frame <-
          cbind(results_frame, HRs, HRs_floated, n_by_group, mean_exposure)
      }
      
      
      # CHECK THAT n and n events match by different routes
      nsum <- sum(results_frame[,  as.vector(outer(c("n"), fac_levels, paste, sep = "_"))])
      n_eventsum <- sum(results_frame[,  as.vector(outer(c("n_event"), fac_levels, paste, sep = "_"))])
      if ((results_frame$n != nsum)|(results_frame$n_event != n_eventsum)){
        stop("Mismatch between numbers derived from different sources. Recheck model. May be that some rows are being excluded due to missing covariate data.")
      }
      
      
      # BIND INTO FINAL RESULTS FRAME AND DELETE
      results_tab <- rbind(results_tab, results_frame)
      
      rm(results_frame)
      
    }
  }
  
  assign(paste0(exposure, "_results_tab"), results_tab)
  write.csv(results_tab, paste0("outputs/", exposure, "_tab.csv"))
  # print(results_tab)
  rm(results_tab, results_columns)
}
```

```{r}

dat2yr <- dat2yr %>%
  mutate(step_thirdsEqual = case_when(
    med_steps < 5000 ~ "<5000",
    med_steps >= 5000 & med_steps <= 10000 ~ "5000-10000",
    med_steps > 10000 ~ ">10000"
  ))

dat2yr$step_thirds <- qtile_cut(dat2yr$med_steps, probs = seq(0, 1, by = 1/3), dp_label = 1)

dat2yr$acc_thirds <- qtile_cut(dat2yr$overall_activity, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat2yr$tdi_quarters <- qtile_cut(dat2yr$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
dat2yr$cadence30_thirds <- qtile_cut(dat2yr$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=1/3))
dat2yr$age_gp_crude <- cut(dat2yr$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
dat2yr$BMI_cats <-
  cut(dat2yr$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<24.9", "25.0-29.9", "30.0+"),
      right = FALSE)
```


Cadence plotting - 2 year
```{r}
for (exposure in exposures) {
  # SET UP RECORDING FRAME ======================================================
  results_columns <-   c("Exposure",
                         "Outcome",
                         "Model",
                         "Adjustment",
                         "n",
                         "n_event",
                         as.vector(outer(
                           # excessively complex code to get crossed column names
                           c(
                             "HR",
                             "Lower_CI",
                             "Upper_CI",
                             "floatedlnHR",
                             "floatedSE",
                             "floatedHR",
                             "floatedLower_CI",
                             "floatedUpper_CI",
                             "n",
                             "n_event", 
                             "mean_steps", 
                             "mean_acc",
                             "mean_cad30"
                           ),
                           unique(dat2yr[, exposure]),
                           paste,
                           sep = "_"
                         )))
  results_tab <-
    data.frame(matrix(ncol = length(results_columns) ,
                      nrow = 0))
  colnames(results_tab) <- results_columns
  
  # Do modelling: ===============================================================
  for (i in 1:length(outcomes)) {
    for (j in 1:length(adjustments)) {
      # Pull relevant values-----------------------------
      outcome <- outcomes[i]
      model_name <- names(adjustments)[j]
      covs <- adjustments[[j]]
      
      # Organise for model calculation-------------------
      cov_sum <- paste0(c(exposure, covs), collapse = "+")
      
      # Model--------------------------------------------
      form <-
        paste0("Surv(age_entry_days, age_exit_days, ",
               outcome,
               ") ~ ",
               cov_sum)
      model <-
        coxph(as.formula(form), dat2yr)
      print(cox.zph(model))
      
      # Extract values-----------------------------------
      results_frame <-
        data.frame(
          "Exposure" = exposure,
          "Outcome" = outcome,
          "Model" = model_name,
          "Adjustment" = paste0(covs, collapse = ","),
          "n" = model$n,
          "n_event" = model$nevent
        )
      
      # CYCLE THROUGH EXPOSURE LEVELS EXTRACTING INFO=============================================
      fac_levels <- levels(factor(dat2yr[, exposure]))
      for (cat in fac_levels) {
        
        # HRs=====================================================================================
        if (cat == fac_levels[1]) {
          HRs <- data.frame(matrix(c(1, 1, 1), nrow = 1))
        }
        else {
          HRs <-
            summary(model)$conf.int[paste0(exposure, cat), c("exp(coef)", "lower .95", "upper .95"), drop = FALSE]
          rownames(HRs) <- NULL
        }
        colnames(HRs) <-
          as.vector(outer(c("HR", "Lower_CI", "Upper_CI"), cat, paste, sep = "_"))
        
        # FLOATED HRs etc =======================================================================
        float_model <- float(model)# This is doing floating absolute risks using Epi package
        
        ## Values
        zval <- qnorm(0.975)
        se <- sqrt(float_model$var[cat])
        lnhr <- float_model$coef[cat]
        
        # Collate into frame
        HRs_floated <-
          data.frame(matrix(c(
            lnhr,
            se,
            exp(lnhr),
            exp(lnhr - se[cat] * zval),
            exp(lnhr + se[cat] * zval)
          ), nrow = 1))
        colnames(HRs_floated) <-
          as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "floatedHR",
              "floatedLower_CI",
              "floatedUpper_CI"
            ),
            cat,
            paste,
            sep = "_"
          ))
    
        # n and nevent ===================================================================================
        n_group <- nrow(dat2yr[dat2yr[, exposure] == cat, ])
        n_event_group <- nrow(dat2yr[(dat2yr[, exposure] == cat) & (dat2yr[, outcome]), ])
        n_by_group <- data.frame(matrix(c(n_group, n_event_group), nrow = 1))
        colnames(n_by_group) <-
          as.vector(outer(c("n", "n_event"), cat, paste, sep = "_"))
        
        # Mean exposure ==================================================================================
        col_me <- paste0("mean_steps_", cat)
        col_acc <- paste0("mean_acc_", cat)
        col_cad30 <- paste0("mean_cad30_", cat)
        mean_exposure <- data.frame(mean(dat2yr$med_steps[dat2yr[, exposure] == cat]), 
                                    mean(dat2yr$overall_activity[dat2yr[, exposure] == cat]),
                                    mean(dat2yr$CadencePeak30Adjusted.steps.min.[dat2yr[, exposure] == cat]))
        colnames(mean_exposure) <- c(col_me, col_acc,col_cad30)
        
        # Bind together in final data frame ==============================================================
        results_frame <-
          cbind(results_frame, HRs, HRs_floated, n_by_group, mean_exposure) 
      }
      
      
      # CHECK THAT n and n events match by different routes
      nsum <- sum(results_frame[,  as.vector(outer(c("n"), fac_levels, paste, sep = "_"))])
      n_eventsum <- sum(results_frame[,  as.vector(outer(c("n_event"), fac_levels, paste, sep = "_"))])
      if ((results_frame$n != nsum)|(results_frame$n_event != n_eventsum)){
        stop("Mismatch between numbers derived from different sources. Recheck model. May be that some rows are being excluded due to missing covariate data.")
      }
      
      
      # BIND INTO FINAL RESULTS FRAME AND DELETE
      results_tab <- rbind(results_tab, results_frame)
      
      rm(results_frame)
      
    }
  }
  
  assign(paste0(exposure, "_results_tab_2yr"), results_tab)
  write.csv(results_tab, paste0("outputs/", exposure, "_tab_2yr.csv"))
  # print(results_tab)
  rm(results_tab, results_columns)
}
```



```{r}

dat3yr <- dat3yr %>%
  mutate(step_thirdsEqual = case_when(
    med_steps < 5000 ~ "<5000",
    med_steps >= 5000 & med_steps <= 10000 ~ "5000-10000",
    med_steps > 10000 ~ ">10000"
  ))

dat3yr$step_thirds <- qtile_cut(dat3yr$med_steps, probs = seq(0, 1, by = 1/3), dp_label = 1)

dat3yr$acc_thirds <- qtile_cut(dat3yr$overall_activity, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat3yr$tdi_quarters <- qtile_cut(dat3yr$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
dat3yr$cadence30_thirds <- qtile_cut(dat3yr$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=1/3))
dat3yr$age_gp_crude <- cut(dat3yr$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
dat3yr$BMI_cats <-
  cut(dat3yr$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<24.9", "25.0-29.9", "30.0+"),
      right = FALSE)
```


```{r}

dat4yr <- dat4yr %>%
  mutate(step_thirdsEqual = case_when(
    med_steps < 5000 ~ "<5000",
    med_steps >= 5000 & med_steps <= 10000 ~ "5000-10000",
    med_steps > 10000 ~ ">10000"
  ))

dat4yr$step_thirds <- qtile_cut(dat4yr$med_steps, probs = seq(0, 1, by = 1/3), dp_label = 1)

dat4yr$acc_thirds <- qtile_cut(dat4yr$overall_activity, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat4yr$tdi_quarters <- qtile_cut(dat4yr$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
dat4yr$cadence30_thirds <- qtile_cut(dat4yr$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=1/3))
dat4yr$age_gp_crude <- cut(dat4yr$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
dat4yr$BMI_cats <-
  cut(dat4yr$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<24.9", "25.0-29.9", "30.0+"),
      right = FALSE)
```


Cadence plotting
```{r}
for (exposure in exposures) {
  # SET UP RECORDING FRAME ======================================================
  results_columns <-   c("Exposure",
                         "Outcome",
                         "Model",
                         "Adjustment",
                         "n",
                         "n_event",
                         as.vector(outer(
                           # excessively complex code to get crossed column names
                           c(
                             "HR",
                             "Lower_CI",
                             "Upper_CI",
                             "floatedlnHR",
                             "floatedSE",
                             "floatedHR",
                             "floatedLower_CI",
                             "floatedUpper_CI",
                             "n",
                             "n_event", 
                             "mean_steps", 
                             "mean_acc",
                             "mean_cad30"
                           ),
                           unique(dat4yr[, exposure]),
                           paste,
                           sep = "_"
                         )))
  results_tab <-
    data.frame(matrix(ncol = length(results_columns) ,
                      nrow = 0))
  colnames(results_tab) <- results_columns
  
  # Do modelling: ===============================================================
  for (i in 1:length(outcomes)) {
    for (j in 1:length(adjustments)) {
      # Pull relevant values-----------------------------
      outcome <- outcomes[i]
      model_name <- names(adjustments)[j]
      covs <- adjustments[[j]]
      
      # Organise for model calculation-------------------
      cov_sum <- paste0(c(exposure, covs), collapse = "+")
      
      # Model--------------------------------------------
      form <-
        paste0("Surv(age_entry_days, age_exit_days, ",
               outcome,
               ") ~ ",
               cov_sum)
      model <-
        coxph(as.formula(form), dat4yr)
      print(cox.zph(model))
      
      # Extract values-----------------------------------
      results_frame <-
        data.frame(
          "Exposure" = exposure,
          "Outcome" = outcome,
          "Model" = model_name,
          "Adjustment" = paste0(covs, collapse = ","),
          "n" = model$n,
          "n_event" = model$nevent
        )
      
      # CYCLE THROUGH EXPOSURE LEVELS EXTRACTING INFO=============================================
      fac_levels <- levels(factor(dat4yr[, exposure]))
      for (cat in fac_levels) {
        
        # HRs=====================================================================================
        if (cat == fac_levels[1]) {
          HRs <- data.frame(matrix(c(1, 1, 1), nrow = 1))
        }
        else {
          HRs <-
            summary(model)$conf.int[paste0(exposure, cat), c("exp(coef)", "lower .95", "upper .95"), drop = FALSE]
          rownames(HRs) <- NULL
        }
        colnames(HRs) <-
          as.vector(outer(c("HR", "Lower_CI", "Upper_CI"), cat, paste, sep = "_"))
        
        # FLOATED HRs etc =======================================================================
        float_model <- float(model)# This is doing floating absolute risks using Epi package
        
        ## Values
        zval <- qnorm(0.975)
        se <- sqrt(float_model$var[cat])
        lnhr <- float_model$coef[cat]
        
        # Collate into frame
        HRs_floated <-
          data.frame(matrix(c(
            lnhr,
            se,
            exp(lnhr),
            exp(lnhr - se[cat] * zval),
            exp(lnhr + se[cat] * zval)
          ), nrow = 1))
        colnames(HRs_floated) <-
          as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "floatedHR",
              "floatedLower_CI",
              "floatedUpper_CI"
            ),
            cat,
            paste,
            sep = "_"
          ))
    
        # n and nevent ===================================================================================
        n_group <- nrow(dat4yr[dat4yr[, exposure] == cat, ])
        n_event_group <- nrow(dat4yr[(dat4yr[, exposure] == cat) & (dat4yr[, outcome]), ])
        n_by_group <- data.frame(matrix(c(n_group, n_event_group), nrow = 1))
        colnames(n_by_group) <-
          as.vector(outer(c("n", "n_event"), cat, paste, sep = "_"))
        
        # Mean exposure ==================================================================================
        col_me <- paste0("mean_steps_", cat)
        col_acc <- paste0("mean_acc_", cat)
        col_cad30 <- paste0("mean_cad30_", cat)
        mean_exposure <- data.frame(mean(dat4yr$med_steps[dat4yr[, exposure] == cat]), 
                                    mean(dat4yr$overall_activity[dat4yr[, exposure] == cat]),
                                    mean(dat4yr$CadencePeak30Adjusted.steps.min.[dat4yr[, exposure] == cat]))
        colnames(mean_exposure) <- c(col_me, col_acc,col_cad30)
        
        # Bind together in final data frame ==============================================================
        results_frame <-
          cbind(results_frame, HRs, HRs_floated, n_by_group, mean_exposure)
      }
      
      
      # CHECK THAT n and n events match by different routes
      nsum <- sum(results_frame[,  as.vector(outer(c("n"), fac_levels, paste, sep = "_"))])
      n_eventsum <- sum(results_frame[,  as.vector(outer(c("n_event"), fac_levels, paste, sep = "_"))])
      if ((results_frame$n != nsum)|(results_frame$n_event != n_eventsum)){
        stop("Mismatch between numbers derived from different sources. Recheck model. May be that some rows are being excluded due to missing covariate data.")
      }
      
      
      # BIND INTO FINAL RESULTS FRAME AND DELETE
      results_tab <- rbind(results_tab, results_frame)
      
      rm(results_frame)
      
    }
  }
  
  assign(paste0(exposure, "_results_tab_4yr"), results_tab)
  write.csv(results_tab, paste0("outputs/", exposure, "_tab_4yr.csv"))
  # print(results_tab)
  rm(results_tab, results_columns)
}
```


Sequential adjustment plots 

```{r}
Full <- coxph((Surv(age_entry_days, age_exit_days, PsATotal_incident)) ~ 
                           (med_steps_std) +as.factor(sex) +as.factor(tdi_quarters)+as.factor(qualif) + as.factor(smoking) +as.factor(alcohol),
                          data=dat)

summary(Full)
```

```{r}
TwoYr <- coxph((Surv(age_entry_days, age_exit_days, PsATotal_incident)) ~ 
                           (med_steps_std) +as.factor(sex) +as.factor(tdi_quarters)+as.factor(qualif) + as.factor(smoking) +as.factor(alcohol),
                          data=dat2yr)

summary(TwoYr)
```

```{r}
FourYr <- coxph((Surv(age_entry_days, age_exit_days, PsATotal_incident)) ~ 
                           (med_steps_std) +as.factor(sex) +as.factor(tdi_quarters)+as.factor(qualif) + as.factor(smoking) +as.factor(alcohol),
                          data=dat4yr)

FourYearSummary <- summary(FourYr)
FourYearSummary

```


```{r}
data <- data.frame(
  Model = c("Full follow-up", "Removal first 2 years", "Removal first 4 years"),
  HR_per_1000_step_increase = c(0.90, 0.91, 0.95),
  CI_lower = c(0.85, 0.85, 0.88),
  CI_upper = c(0.96, 0.97, 1.00),
  Cases_n = c("99 / 2604", "77 / 2582", "52 / 2557")
)

data$Model <- factor(data$Model, levels = c("Removal first 4 years", "Removal first 2 years", "Full follow-up"))

```


```{r}

forest_plot <- ggplot(data, aes(x = HR_per_1000_step_increase, y = Model, xmin = CI_lower, xmax = CI_upper)) +
  geom_point(size = 2) +
  geom_errorbarh(height = 0) +
  geom_point(aes(size = 1), shape = 15, colour = "black", fill = "black", stroke = 0.5) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "red") +
  labs(x = "Hazard Ratio (95% CI) per 1000 step increase", y = "") +
  scale_x_continuous(breaks = c(0.2,0.4, 0.6, 0.8, 1.0, 1.2, 1.4), limits = c(0.15, 1.45)) +
  theme_classic() +
  theme(
    axis.line.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    strip.text.x = element_blank(),
    strip.text.y = element_blank(),
    panel.spacing = unit(5, "lines"),
    panel.spacing.y = unit(2, "lines"),
    plot.margin = margin(20, 50, 10, 10, "points")
  ) +
  coord_cartesian(clip = "off")

# Add text annotations
forest_plot <- forest_plot +
  # HR column - contents
  geom_text(aes(y = Model, x = 1.1, label = sprintf("HR: %.2f (%.2f-%.2f)", HR_per_1000_step_increase, CI_lower, CI_upper)), 
            hjust = -0.2, vjust = 0, size = 3.7, color = "black") +
  # HR column - label bolded at top
  geom_text(aes(y = Model, x = 1.2, label = ifelse(Model == "Full follow-up", "HR (95% CI)", NA)),
            hjust = 0, vjust = -1.8, size = 3.7, color = "black", fontface = "bold", 
            parse = FALSE, check_overlap = TRUE) +
  # Cases column - content
  geom_text(aes(y = Model, x = 0.65, label = Cases_n),
            hjust = 0, vjust = 0, size = 3.7, color = "black") +
  # Cases column - label bolded at top
  geom_text(aes(y = Model, x = 0.65, label = ifelse(Model == "Full follow-up", "Cases / n", NA)),
            hjust = 0.05, vjust = -1.8, size = 3.7, color = "black", fontface = "bold", 
            parse = FALSE, check_overlap = TRUE) +
  # Model names
  geom_text(aes(y = Model, x = 0.25, label = Model),
            hjust = 0, vjust = 0, size = 3.7, color = "black") +
  # Model titles in bold
  geom_text(aes(y = Model, x = 0.25, label = ifelse(Model == "Full follow-up", "Model", NA)),
            hjust = 0, vjust = -1.8, size = 3.7, color = "black", fontface = "bold",
            parse = FALSE)

# Display the plot
print(forest_plot)
```


```{r}
forest_plot <- ggplot(data, aes(x = HR_per_1000_step_increase, y = Model, xmin = CI_lower, xmax = CI_upper)) +
  geom_point(size = 2) +
  geom_errorbarh(height = 0) +
  geom_point(aes(size = 1), shape = 15, colour = "black", fill = "black", stroke = 0.5) +
  geom_vline(xintercept = 1, linetype = "solid", color = "lightgrey") +
  scale_size(guide = NULL) + 
  labs(x = "Hazard Ratio (95% CI) per 1000 step increase", y = "") +
  scale_x_continuous(breaks = c(0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4), limits = c(0.15, 1.45)) +
  theme_classic() +
  theme(
    axis.line.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    strip.text.x = element_blank(),
    strip.text.y = element_blank(),
    panel.spacing = unit(5, "lines"),
    panel.spacing.y = unit(2, "lines"),
    plot.margin = margin(20, 50, 10, 10, "points")
  ) +
  coord_cartesian(clip = "off")

# Add text annotations
forest_plot <- forest_plot +
  # HR column - contents
  geom_text(aes(y = Model, x = 1.1, label = sprintf("%.2f (%.2f, %.2f)", HR_per_1000_step_increase, CI_lower, CI_upper)), 
            hjust = -0.2, vjust = 0, size = 4, color = "black", fontface = "bold") +
  # HR column - label bolded at top
  geom_text(aes(y = Model, x = 1.1, label = ifelse(Model == "Full follow-up", "Hazard Ratio (95% CI)", NA)),
            hjust = 0, vjust = -1.8, size = 4, color = "black", fontface = "bold", 
            parse = FALSE, check_overlap = TRUE) +
  # Cases column - content
  geom_text(aes(y = Model, x = 0.65, label = Cases_n),
            hjust = 0, vjust = 0, size = 4, color = "black", fontface = "bold") +
  # Cases column - label bolded at top
  geom_text(aes(y = Model, x = 0.65, label = ifelse(Model == "Full follow-up", "Cases / n", NA)),
            hjust = 0.05, vjust = -1.8, size = 4, color = "black", fontface = "bold", 
            parse = FALSE, check_overlap = TRUE) +
  # Model names
  geom_text(aes(y = Model, x = 0.23, label = Model),
            hjust = 0, vjust = 0, size = 4, color = "black", fontface = "bold") +
  # Model titles in bold
  geom_text(aes(y = Model, x = 0.23, label = ifelse(Model == "Full follow-up", "Model", NA)),
            hjust = 0, vjust = -1.8, size = 4, color = "black", fontface = "bold",
            parse = FALSE)

# Display the plot
print(forest_plot)
```

```{r}
dir.create("plots")
output_dir <- "plots"
output_file <- file.path(output_dir, "forest.tiff")
ggsave(output_file, forest_plot, device = "tiff", width = 10, height = 3, dpi = 300)
``` 

