---
title: "d_analyse_data"
format: html
editor: visual
---

## Load data

Data:


```{r}
dat <- fread("prepped_steps.csv", data.table = FALSE) # this file location assumes running in same session as previous script
#dat <- fread("Data/prepped_steps_RA2years.csv", data.table = FALSE)

```


```{r}
library(data.table)
library(plyr)
library(dplyr)
library(magrittr)
library(lubridate)
library(readr)
library(survival)
library(Epi)
library(emmeans)
library(ggplot2)
#library(survminer)
#library(ckbplotr)

dir.create("outputs")
```

## Set-up useful functions

```{r}
source("rounding_functions.R")
source("cut_by_quantile.R")
source("cox_functions.R")
```

## Additional data preprocessing

Done in this script not the previous to ensure reference values behave (easy to fix by relevelling otherwise).

```{r}
dat$step_thirds <- qtile_cut(dat$med_steps, probs = seq(0, 1, by = 1/3))
dat$acc_thirds <- qtile_cut(dat$overall_activity, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat$cad30_thirds <- qtile_cut(dat$CadencePeak30Adjusted.steps.min., probs = seq(0, 1, by = 1/3))
dat$tdi_quarters <- qtile_cut(dat$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
dat$cadence30_quarters <- qtile_cut(dat$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=0.25))
dat$age_gp_crude <- cut(dat$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
dat$BMI_cats <-
  cut(dat$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<24.9", "25.0-29.9", "30.0+"),
      right = FALSE)
```

```{r}

primary <- "med_steps"
dat$med_steps_std <- standardise_column(dat[[primary]], 1000, TRUE)
hist(dat$med_steps_std)
```

```{r}
dat <- dat %>%
  mutate(sed_time = sedentary_overall_average * 1440)

dat <- dat %>%
  mutate(mvpa_time = MVPA_overall_average * 1440)
```

```{r}
std_deviation_sed <- sd(dat$sed_time, na.rm = TRUE)
mean_deviation_sed <- mean(dat$sed_time, na.rm = TRUE)
```

```{r}
sd(dat$sedentary_overall_average) #3822.266
# Generate a standardization variable
dat$sed_std = dat$sed_time - (mean_deviation_sed/std_deviation_sed)
# Check distribution of variable
hist(dat$sed_std)
```

```{r}
std_deviation_MVPA <- sd(dat$mvpa_time, na.rm = TRUE)
mean_deviation_MVPA <- mean(dat$mvpa_time, na.rm = TRUE)
```

```{r}

# Generate a standardization variable
dat$mvpa_std = dat$mvpa_time - (mean_deviation_MVPA/std_deviation_MVPA)
# Check distribution of variable
hist(dat$mvpa_std)
```

```{r}
cox_BMI_cad <- coxph((Surv(age_entry_days, age_exit_days, PsA_incident_total)) ~ 
                           sed_std,
                         data=dat)
 
summary(cox_BMI_cad) 

```

```{r}
cox_PRS <- coxph((Surv(age_entry_days, age_exit_days, PsA_incident_total)) ~ 
                           mvpa_std +as.factor(ethnicity) + as.factor(tdi_quarters)
                 +as.factor(smoking) +
                   as.factor(alcohol),
                         data=dat)

summary(cox_PRS)

```



```{r}
datPsO <- dat %>%
  filter(total_prevalent_PsO == TRUE)
```

```{r}
std_deviation_MVPA <- sd(datPsO$mvpa_time, na.rm = TRUE)
mean_deviation_MVPA <- mean(datPsO$mvpa_time, na.rm = TRUE)
```

```{r}

# Generate a standardization variable
datPsO$mvpa_std_PsO = datPsO$mvpa_time - (mean_deviation_MVPA/std_deviation_MVPA)
# Check distribution of variable
hist(dat$mvpa_std)
```

```{r}
cox_PRS <- coxph((Surv(age_entry_days, age_exit_days, PsA_incident_total)) ~ 
                           CadencePeak30Adjusted.steps.min. 
                 +as.factor(smoking),
                         data=datPsO)

summary(cox_PRS)

```
