---
title: "plot_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(plyr)
library(dplyr)
library(magrittr)
library(lubridate)
library(readr)
library(survival)
library(Epi)
library(emmeans)
library(ggplot2)
#library(ckbplotr)
```

## Set-up useful functions
```{r}
source("rounding_functions.R")
source("cut_by_quantile.R")
source("cox_functions.R")
```

Reread data: 
```{r}
dat <- fread("PsAfinal/prepped_steps_PsAfinal.csv", data.table = FALSE) 

dat$V1 <- NULL

dat <- dat %>%
  filter(total_prevalent_PsO == TRUE)
```



```{r}
dat <- dat %>%
  mutate(step_thirds = case_when(
    med_steps < 5000 ~ "<5000",
    med_steps >= 5000 & med_steps <= 10000 ~ "5000-10000",
    med_steps > 10000 ~ ">10000"
  ))

dat$step_thirds <- qtile_cut(dat$med_steps, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat$acc_thirds <- qtile_cut(dat$overall_activity, probs = seq(0, 1, by = 1/3), dp_label = 1)
dat$tdi_quarters <- qtile_cut(dat$tdi_raw, probs = seq(0, 1, by = 0.25), dp_label = 1)
dat$cadence30_thirds <- qtile_cut(dat$CadencePeak30Adjusted.steps.min., probs = seq(0,1, by=1/3))
dat$age_gp_crude <- cut(dat$age_entry_years, seq(40, 80, by = 10), right = FALSE, labels = c("40-49", "50-59", "60-69", "70-79"))
dat$BMI_cats <-
  cut(dat$BMI,
      breaks = c(0, 25, 30, 10000),
      labels = c("<24.9", "25.0-29.9", "30.0+"),
      right = FALSE)
```

Sequentially run this - for sensitivity analysis
```{r}
TwoYear_cases <- (dat$PsATotal_incident & dat$fu_time <= 730)

dat <- dat[!(TwoYear_cases), ]

```

Results: - select which sensitivity you want to run through 
```{r}
step_thirds_results_tab <- fread("outputs/step_thirds_tab.csv", data.table = FALSE) 
```


Organise results to plot and iteratively produce shape plots with different settings: 
```{r}
exposures <- c("step_thirds")
outcomes <- c("PsATotal_incident")

adjustments <- unique(step_thirds_results_tab$Adjustment)

# CYCLE OVER ADJUSTMENTS=========================================
 for (adjustment in adjustments) {
   
  # CYCLE OVER OUTCOMES ============================
  for (outcome in outcomes) {
      
      # PROCESS OUTCOME NAME ======================================
      if (outcome == "PsATotal_incident") {
        outcome_title <- "Incident PsA"
      }  else {
        print(outcome)
        stop("Unrecognised outcome value")
      }
      
   
  # CYCLE OVER EXPOSURES =================================================
  for (exposure in exposures) {
    print(exposure)
      
  # PROCESS EXPOSURE NAME ==========================================
  if (exposure == "step_thirds") {
    exposure_title <- "Median Daily Steps"
  }
  else if (exposure == "acc_thirds") {
    exposure_title <- "Overall Acceleration (mg)"
  }
  else {
    stop("Unrecognised exposure value")
  }
  
  # GET RELEVANT DATASET =================================================
  tab <- get(paste0(exposure, "_results_tab"))
  
  
  
      # EXTRACT RELEVANT ELEMENTS OF DATASET=============================
      rel_tab <- tab[(tab$Outcome == outcome) & (tab$Adjustment == adjustment), , drop = FALSE]
      
      cols <- colnames(tab)[grepl("floatedlnHR_", colnames(tab))]
      cats <- sub("floatedlnHR_", "", cols)
        
      fp_frame <-
        data.frame(
          "exposure" = rep(exposure_title, length(cats)),
          "variable" = cats,
          "estimate" = rep(NA, length(cats)),
          "stderr" = rep(NA, length(cats)),
          "n" = rep(NA, length(cats)),
          "n_event" = rep(NA, length(cats))
        )
      for (cat in cats){
        fp_frame[fp_frame$variable == cat, c("estimate", "stderr", "n", "n_event", "mean_steps")] <- rel_tab[, as.vector(outer(
            c(
              "floatedlnHR",
              "floatedSE",
              "n", 
              "n_event", 
              "mean_steps"
            ),
            cat,
            paste,
            sep = "_"
          ))]
      }
      fp_frame$nlab <- format_thousand(fp_frame$n_event)
      fp_frame$estlab <- round_2_dp(exp(fp_frame$estimate)) 
      assign(paste0("fp_frame_", exposure, "_", outcome), fp_frame)
  }
  

  } 
   
   ## Set up for shape plots -------------------------------------------------------------------------------

  ### Manual --------------------------------------------------------------------------------------------
  # Allows fine-grained control over plot appearance
  rat_val <- 1.5
  size_val <- 14
  line_val <- 0.7
  textsize <- 5.5
  ext <- c(0, 0)
  lim_rad_scale <- 1/min(fp_frame_step_thirds_PsATotal_incident$stderr) + 1
  ybreaks <- c(0.25, 0.5, 1,1.5, 2)  # Include 2 in the breaks
  ylim_scale <- 1

  ylims <- c(ybreaks[1] / ylim_scale, ybreaks[length(ybreaks)] * ylim_scale)
# Calculate the limits for the y-axis
 #ylims <- c(ybreaks[1] - 0.02, ybreaks[length(ybreaks)] + 0.01)
  xlims <- c(0, quantile(dat$med_steps, 0.99))
  

  ruglinewidth <- 0.03
  datatoplot <- fp_frame_step_thirds_PsATotal_incident
  
  # Create the plot with main aesthetics
shapeplot1 <- ggplot(datatoplot, aes(x = `mean_steps`, y = exp(estimate))) +

  # Plot the point estimates
  geom_point(aes(size = 1/stderr),
             shape = 15,
             colour = "black",
             fill = "black",
             stroke = 0.5) +
  
  # Plot point estimates text
  geom_text(aes(y = exp(estimate+1.96*stderr),
                label = estlab),
            vjust = -0.15,
            size  = textsize,
            colour = "black") +
  
  # Plot n events text
  geom_text(aes(y = exp(estimate-1.96*stderr),
                label = nlab),
            vjust = 1.15,
            size  = textsize,
            colour = "black") +
  
  # Plot the CIs
  geom_linerange(aes(ymin = exp(estimate-1.96*stderr),
                     ymax = exp(estimate+1.96*stderr)),
                 colour = "black",
                 linewidth = 0.5) +
  
  # Set the scale for the size of boxes
  scale_radius(guide  = "none",
               limits = c(0, lim_rad_scale),
               range  = c(0, 5)) +
  
  # Use identity for aesthetic scales
  scale_shape_identity() +
  scale_colour_identity() +
  scale_fill_identity() +
  
  # Set the y-axis scale 
 #scale_y_continuous(breaks = breaks)+
 # scale_y_continuous(trans  = "log",
  #                     breaks = ybreaks * ylim_scale) +
  scale_y_continuous(
  trans = "log",
  breaks = ybreaks * ylim_scale,
  limits = ylims)+
  
  scale_x_continuous(expand = c(0, 0), limits = c(0, 21000)) +
  

  # coord_cartesian(ylim = c(0, 2))+
  #scale_x_continuous(labels = function(x) {format_thousand(x)}) + 
  
  
  
  # Add titles
   xlab("Median Step Count") +
  ylab("HR for Incident PsA") + 

 # Add rug plot
  geom_rug(data = dat[dat$med_steps < quantile(dat$med_steps, 0.99), ], mapping = aes(x = med_steps), inherit.aes = FALSE, linewidth = ruglinewidth, alpha = 0.5,length = unit(0.015, "npc")) +
  theme(aspect.ratio = 1.8) +
  theme_bw() +
  theme(axis.title.x = element_text(size = 17, color = "black", face="bold"),
        axis.title.y = element_text(size = 17, color = "black", face="bold"),
        axis.text.x = element_text(size=15, colour = "black"),
        axis.text.y = element_text(size=15, colour = "black"))
  

  svg(paste0("outputs/shapeplot_stepthirds_", gsub(",", "_", adjustment), Sys.Date(), ".svg"), width = 10, height = 6)
  dev.off()
  
  assign(paste0("shapeplot_PsATotal_incident_step_thirds_", gsub(",", "_", adjustment)), shapeplot1)
   }
```

```{r}
dir.create("plots")
output_dir <- "plots"
output_file <- file.path(output_dir, "PsA_fig_2yrSens.tiff")
ggsave(output_file, shapeplot_PsATotal_incident_step_thirds_sex_tdi_quarters_qualif_smoking_alcohol, device = "tiff", width = 8, height = 8, dpi = 300)
```